version: '3.9'
services:
  workspace:
    build:
      context: docker/workspace
      args:
        PUID: ${PUID:-1000}
        PGID: ${PGID:-1000}
    volumes:
      - .:/var/www/html
      - ~/.composer:/home/user/.composer # Composer caching
      - ~/.ssh:/home/user/.ssh # Installing packages and GitHub auth
    tty: true
