name: Tests

on:
  - push
  - pull_request

jobs:
  main:
    strategy:
      matrix:
        php-versions: [ '7.3', '7.4', '8.0' ]

    name: Tests on PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-20.04
    env:
      key: cache-v1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ matrix.php-versions }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-${{ matrix.php-versions }}-

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: pcov
          tools: composer:v2

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Run PHPStan
        run: composer phpstan -- --no-progress

      - name: Run PHP CS Fixer
        run: composer phpcsfixer -- --stop-on-violation

      - name: Run tests
        run: composer test
